name: ios_machine_to_model
description: A Flutter package to translate ios machine to model.
version: 1.0.0
author: Ji Tao <jitao@jitao.tech>
homepage: https://jitao.tech

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
