name: ios_machine_to_model
description: A Flutter package to translate ios machine code to model. The machine code is retrieved using device_info plugin.
version: 1.2.0
author: Ji Tao <jitao@jitao.tech>
homepage: https://github.com/flmn/ios_machine_to_model

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
